#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : ladspa_sdk
Version  : 1.15
Release  : 1
URL      : http://www.ladspa.org/download/ladspa_sdk_1.15.tgz
Source0  : http://www.ladspa.org/download/ladspa_sdk_1.15.tgz
Summary  : No detailed summary available
Group    : Development/Tools
License  : LGPL-2.1
Requires: ladspa_sdk-bin = %{version}-%{release}
Requires: ladspa_sdk-lib = %{version}-%{release}
Requires: ladspa_sdk-license = %{version}-%{release}

%description
LADSPA SDK
----------
The API itself can be be found in src/ladspa.h. The rest of this
package is a software development kit to make the API even easier to
work with.

%package bin
Summary: bin components for the ladspa_sdk package.
Group: Binaries
Requires: ladspa_sdk-license = %{version}-%{release}

%description bin
bin components for the ladspa_sdk package.


%package dev
Summary: dev components for the ladspa_sdk package.
Group: Development
Requires: ladspa_sdk-lib = %{version}-%{release}
Requires: ladspa_sdk-bin = %{version}-%{release}
Provides: ladspa_sdk-devel = %{version}-%{release}
Requires: ladspa_sdk = %{version}-%{release}
Requires: ladspa_sdk = %{version}-%{release}

%description dev
dev components for the ladspa_sdk package.


%package lib
Summary: lib components for the ladspa_sdk package.
Group: Libraries
Requires: ladspa_sdk-license = %{version}-%{release}

%description lib
lib components for the ladspa_sdk package.


%package license
Summary: license components for the ladspa_sdk package.
Group: Default

%description license
license components for the ladspa_sdk package.


%prep
%setup -q -n ladspa_sdk_1.15

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1560050969
unset LD_AS_NEEDED
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$CFLAGS -fno-lto "
export FFLAGS="$CFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
pushd src
make
popd


%install
export SOURCE_DATE_EPOCH=1560050969
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/ladspa_sdk
cp doc/COPYING %{buildroot}/usr/share/package-licenses/ladspa_sdk/doc_COPYING
pushd src
%make_install INSTALL_PLUGINS_DIR=%{buildroot}/usr/lib64/ladspa  INSTALL_INCLUDE_DIR=%{buildroot}/usr/include INSTALL_BINARY_DIR=%{buildroot}/usr/bin
popd

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/analyseplugin
/usr/bin/applyplugin
/usr/bin/listplugins

%files dev
%defattr(-,root,root,-)
/usr/include/*.h

%files lib
%defattr(-,root,root,-)
/usr/lib64/ladspa/amp.so
/usr/lib64/ladspa/delay.so
/usr/lib64/ladspa/filter.so
/usr/lib64/ladspa/noise.so
/usr/lib64/ladspa/sine.so

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/ladspa_sdk/doc_COPYING
